import type { Metadata } from 'next';
import './globals.css';
import { inter } from '@/config/fonts';
import { ReactNode } from 'react';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    );
}
